### ISSUE TITLE
Build of fgt-dev fails with MVCC_READ_CONFLICT

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/blockchain-hlf-workspace#3]
During the build of fgt 
```sh
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ ./bootCompose.sh eth-dev
```

fgt-workspace:
```txt
2022-05-12T14:59:20.324110999Z 172.16.63.64:8080 - [2022-05-12T14:59:18.283Z] PUT:/anchor/traceability/create-anchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpMJAUrjzm4WSuzf8QPXRskZJoUmRBM7zgLrYVwsZgmENmq47Ww3ysr6gkZ3cJo5p8SMhbFH92RtSZ9ek8U
xdTqu6hkVmDpBvsHdA7GBrA4wrhGXbBKUxYPGMy6X/4qnrBhooj78L2psbyjJ44LqFA4DA5yiTsCjuUiS7XhziHCiWC2pZm8BxQJoALd9QvakVYni5cZvKydtUwxo8Tj6h2snBD7GeBq7Dweo2En8rXrJCvNp52QUeevfF8aQJa2dCqegEFrXz4XSfFqzikjfwj8JR92HGsoRtgPM6LbkjESnVtqrRqc8EiieMA
iN3ayrbVRn24dfncm52uAJPj99yJE9PmqjsKGDBcktiZd 201 2,040.441ms
2022-05-12T14:59:20.334012457Z May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token T in JSON at position 0
2022-05-12T14:59:20.334027397Z     at JSON.parse (<anonymous>)
2022-05-12T14:59:20.334030227Z     at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:40672:42)
2022-05-12T14:59:20.334032877Z     at IncomingMessage.emit (events.js:327:22)
2022-05-12T14:59:20.334043896Z     at endReadableNT (internal/streams/readable.js:1327:12)
2022-05-12T14:59:20.334063146Z     at processTicksAndRejections (internal/process/task_queues.js:80:21)
2022-05-12T14:59:20.334066306Z {
2022-05-12T14:59:20.334068426Z   error: Error: Request Failed.
2022-05-12T14:59:20.334070536Z   Status Code: 500
2022-05-12T14:59:20.334072636Z   URL: 172.16.16.16:3000/createAnchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoYKGdBqcjJKP8QKEjFr3PpwcE7rvmvW83GsVnxAcrfzHUZAi4eWh4nukicffsJcjpY8GMkugeWLU4oK1mK9kHL4VSg7p3xzWpJBc9ihVxaK7JRX9Yn9k9kk9Lvs/4qnrBhooj78L2psbyjJ44LqFA4DA5wrRbdTCpSWu9bWSCpyUbdbhm8T9iauRv1aLcLhSvczZwygfxJFR8V4vGnGySoebQTWAHoEeKnmKmT77TyyeFKxPPpQb4F2x6ucaM7JkSUvi4qFdV7uM75U9XkBCnAhLSTiRzvYEZXCYXkoTpJXtpzPxtAAziQTxRJ9f3QwDb3Un4Udy1WzvDu3jZUcWazZLCBeUHEc1vJjU1d
2022-05-12T14:59:20.334075456Z       at ClientRequest.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:40658:13)
2022-05-12T14:59:20.334077866Z       at Object.onceWrapper (events.js:422:26)
2022-05-12T14:59:20.334080156Z       at ClientRequest.emit (events.js:315:20)
2022-05-12T14:59:20.334082256Z       at HTTPParser.parserOnIncomingClient (_http_client.js:641:27)
2022-05-12T14:59:20.334084496Z       at HTTPParser.parserOnHeadersComplete (_http_common.js:126:17)
2022-05-12T14:59:20.334086626Z       at Socket.socketOnData (_http_client.js:509:22)
2022-05-12T14:59:20.334174264Z       at Socket.emit (events.js:315:20)
2022-05-12T14:59:20.334182304Z       at addChunk (internal/streams/readable.js:309:12)
2022-05-12T14:59:20.334185074Z       at readableAddChunk (internal/streams/readable.js:284:9)
2022-05-12T14:59:20.334187384Z       at Socket.Readable.push (internal/streams/readable.js:223:10)
2022-05-12T14:59:20.334189614Z       at TCP.onStreamRead (internal/stream_base_commons.js:188:23),
2022-05-12T14:59:20.334277433Z   statusCode: 500,
2022-05-12T14:59:20.334281303Z   message: 'TransactionError: Commit of transaction b0c6c84ffb29d8b4407229e7596d08d1e7b1155cb5bf1f92ddc59c89616be536 failed on peer peer0.org1.example.com:7051 with status MVCC_READ_CONFLICT'
2022-05-12T14:59:20.334283863Z }
2022-05-12T14:59:20.334291423Z 172.16.63.62:8080 - [2022-05-12T14:59:18.524Z] PUT:/anchor/traceability/create-anchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoYKGdBqcjJKP8QKEjFr3PpwcE7rvmvW83GsVnxAcrfzHUZAi4eWh4nukicffsJcjpY8GMkugeWLU4oK1mK9kHL4VSg7p3xzWpJBc9ihVxaK7JRX9Yn9k9kk9Lvs/4qnrBhooj78L2psbyjJ44LqFA4DA5wrRbdTCpSWu9bWSCpyUbdbhm8T9iauRv1aLcLhSvczZwygfxJFR8V4vGnGySoebQTWAHoEeKnmKmT77TyyeFKxPPpQb4F2x6ucaM7JkSUvi4qFdV7uM75U9XkBCnAhLSTiRzvYEZXCYXkoTpJXtpzPxtAAziQTxRJ9f3QwDb3Un4Udy1WzvDu3jZUcWazZLCBeUHEc1vJjU1d 500 1,806.049ms
2022-05-12T14:59:20.334294622Z Request logs:
2022-05-12T14:59:20.334296812Z   Generic Error Middleware prevented message to be sent on response.write {"message":"TransactionError: Commit of transaction b0c6c84ffb29d8b4407229e7596d08d1e7b1155cb5bf1f92ddc59c89616be536 failed on peer peer0.org1.example.com:7051 with status MVCC_READ_CONFLICT"} undefined undefined
...
```

Several errors appear on the hlf-adapter, starting with:
```txt
2022-05-12T14:59:18.520164921Z data received :  
2022-05-12T14:59:18.526350216Z Serving PUT /create-anchor :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoYKGdBqcjJKP8QKEjFr3PpwcE7rvmvW83GsVnxAcrfzHUZAi4eWh4nukicffsJcjpY8GMkugeWLU4oK1mK9kHL4VSg7p3xzWpJBc9ihVxaK7JRX9Yn9k9kk9Lvs 4qnrBhooj78L2psbyjJ44LqFA4DA5wrRbdTCpSWu9bWSCpyUbdbhm8T9iauRv1aLcLhSvczZwygfxJFR8V4vGnGySoebQTWAHoEeKnmKmT77TyyeFKxPPpQb4F2x6ucaM7JkSUvi4qFdV7uM75U9XkBCnAhLSTiRzvYEZXCYXkoTpJXtpzPxtAAziQTxRJ9f3QwDb3Un4Udy1WzvDu3jZUcWazZLCBeUHEc1vJjU1d
2022-05-12T14:59:18.526366226Z Call CreateAnchor for : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoYKGdBqcjJKP8QKEjFr3PpwcE7rvmvW83GsVnxAcrfzHUZAi4eWh4nukicffsJcjpY8GMkugeWLU4oK1mK9kHL4VSg7p3xzWpJBc9ihVxaK7JRX9Yn9k9kk9Lvs and [object Object]
2022-05-12T14:59:20.322836238Z 2022-05-12T14:59:20.322Z - warn: [TransactionEventHandler]: strategyFail: commit failure for transaction "b0c6c84ffb29d8b4407229e7596d08d1e7b1155cb5bf1f92ddc59c89616be536": TransactionError: Commit of transaction b0c6c84ffb29d8b4407229e7596d08d1e7b1155cb5bf1f92ddc59c89616be536 failed on peer peer0.org1.example.com:7051 with status MVCC_READ_CONFLICT
2022-05-12T14:59:20.322882238Z     at TransactionEventHandler.eventCallback (/usr/src/app/node_modules/fabric-network/lib/impl/event/transactioneventhandler.js:105:31)
2022-05-12T14:59:20.322939087Z     at CommitListenerSession.notifyListener (/usr/src/app/node_modules/fabric-network/lib/impl/event/commitlistenersession.js:97:18)
2022-05-12T14:59:20.322949357Z     at EventListener.callback (/usr/src/app/node_modules/fabric-network/lib/impl/event/commitlistenersession.js:88:18)
2022-05-12T14:59:20.322972136Z     at EventListener.onEvent (/usr/src/app/node_modules/fabric-common/lib/EventListener.js:124:10)
2022-05-12T14:59:20.322980696Z     at EventService._callTransactionListener (/usr/src/app/node_modules/fabric-common/lib/EventService.js:1051:16)
2022-05-12T14:59:20.323012506Z     at EventService._processTxEvents (/usr/src/app/node_modules/fabric-common/lib/EventService.js:1006:12)
2022-05-12T14:59:20.323020895Z     at ClientDuplexStreamImpl.<anonymous> (/usr/src/app/node_modules/fabric-common/lib/EventService.js:481:12)
2022-05-12T14:59:20.323040605Z     at ClientDuplexStreamImpl.emit (events.js:400:28)
2022-05-12T14:59:20.323048635Z     at addChunk (internal/streams/readable.js:293:12)
2022-05-12T14:59:20.323070885Z     at readableAddChunk (internal/streams/readable.js:267:9) {
2022-05-12T14:59:20.323079255Z   transactionId: 'b0c6c84ffb29d8b4407229e7596d08d1e7b1155cb5bf1f92ddc59c89616be536',
2022-05-12T14:59:20.323100144Z   transactionCode: 'MVCC_READ_CONFLICT'
2022-05-12T14:59:20.323108254Z }
2022-05-12T14:59:20.323132884Z *** createAnchor Result:  <Buffer > 
...
```

**Comment by joaoluis-pdm** [comment]
https://stackoverflow.com/questions/45347439/mvcc-read-conflict-when-submitting-multiple-transactions-concurrently ?

**Comment by joaoluis-pdm** [comment]
An experiment was done on fgt-workspace

[b4074f958972cadfd13222161f3038acfb662157](https://github.com/PharmaLedger-IMI/fgt-workspace/commit/b4074f958972cadfd13222161f3038acfb662157)

... to start the dockers in sequence, and not in parallel.

**Comment by joaoluis-pdm** [comment]
Fixed on PR merge of https://github.com/PharmaLedger-IMI/hf-adapter/commit/ffae36a1d6ce12d1dae4e57a695e46ed038eeb88
