### ISSUE TITLE
TypeError: Cannot read property 'submitTransaction' of undefined

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/blockchain-hlf-workspace#6]
```txt
----- fgt-workspace log -----
...
172.16.63.51:8080 - [2022-09-02T17:55:57.628Z] GET:/anchor/traceability/get-last-version/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoFsx1HF3FCC4gscEvAvxXxW8cfVD
nEAnfHpsDq54VskebcUiQQVPFSGz6RR9qX6AAHr7mDXbHEw9PRUnhndgRpSW3n49rTfiikHpNxwkAabgQi9EszASc7eKpwy 200 25.766ms
Caught an error during JSON.parse TypeError: Cannot read property 'submitTransaction' of undefined
May or not be important, for safety check it! Failed to parse the error from the response due to SyntaxError: Unexpected token T in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:44110:42)
    at IncomingMessage.emit (node:events:538:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
{
  error: Error: Request Failed.
  Status Code: 500
  URL: 172.16.16.16:3000/createAnchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoFsx1HF3FCC4gscEvAvxXxW8cfVDnEAnfHpsDq54VskebcUiQQVPFSGz6RR9qX6AAHr7mDXbHEw9PRUnhndgRpSW3n49rTfiikHpNxwkAabgQi9EszASc7eKpwy/sUcADsUohMh7JeHzG29PxhPEqJi2bcQNMZw3pPrDmhCKEyYou1VqBQNV4Vm79b5gGx1ZzgkapTVNHMHotTA3nv4HsQU6PvwAEEorrSGbKgsu6HuRYYm2cY7GjjvtRgE3uCVSv2gMoDkdEovQmz4yWhXKLWoq4N85RrjjaK4n4572VfqaJjrFxDZqxtu8ahqXVmMXZUZu6q4RHGSV7FuyyW3a8i9NtyCLAsvx9c31
      at ClientRequest.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:44096:13)
      at Object.onceWrapper (node:events:646:26)
      at ClientRequest.emit (node:events:526:28)
      at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
      at Socket.socketOnData (node:_http_client:482:22)
      at Socket.emit (node:events:526:28)
      at addChunk (node:internal/streams/readable:315:12)
      at readableAddChunk (node:internal/streams/readable:289:9)
      at Socket.Readable.push (node:internal/streams/readable:228:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23),
  statusCode: 500,
  message: "TypeError: Cannot read property 'submitTransaction' of undefined"
}
...
```

```txt
----- hlf-adapter -----
...
2022-09-02T17:45:33.159906347Z Connected to HLF network - Anchoring.
2022-09-02T17:45:33.165606210Z Server started. Listening on  3000
2022-09-02T17:55:57.642895519Z Serving GET /get-last-version for  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoFsx1HF3FCC4gscEvAvxXxW8cfVDnEAnfHpsDq54VskebcUiQQVPFSGz6RR9qX6AAHr7mDXbHEw9PRUnhndgRpSW3n49rTfiikHpNxwkAabgQi9EszASc7eKpwy
2022-09-02T17:55:57.687064414Z Serving PUT /create-anchor :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoFsx1HF3FCC4gscEvAvxXxW8cfVDnEAnfHpsDq54VskebcUiQQVPFSGz6RR9qX6AAHr7mDXbHEw9PRUnhndgRpSW3n49rTfiikHpNxwkAabgQi9EszASc7eKpwy sUcADsUohMh7JeHzG29PxhPEqJi2bcQNMZw3pPrDmhCKEyYou1VqBQNV4Vm79b5gGx1ZzgkapTVNHMHotTA3nv4HsQU6PvwAEEorrSGbKgsu6HuRYYm2cY7GjjvtRgE3uCVSv2gMoDkdEovQmz4yWhXKLWoq4N85RrjjaK4n4572VfqaJjrFxDZqxtu8ahqXVmMXZUZu6q4RHGSV7FuyyW3a8i9NtyCLAsvx9c31
2022-09-02T17:55:57.687745231Z Call CreateAnchor for : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoFsx1HF3FCC4gscEvAvxXxW8cfVDnEAnfHpsDq54VskebcUiQQVPFSGz6RR9qX6AAHr7mDXbHEw9PRUnhndgRpSW3n49rTfiikHpNxwkAabgQi9EszASc7eKpwy and [object Object]
2022-09-02T17:56:48.644602042Z Serving GET /get-last-version for  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpyQmeeSJwMxwSSXJiUZfjRKz3kkBXbKauZcFChQjcvY98zR2rFzcBEreoFbEiH8MYYEY3T3B63fuifS9iP3NpKnMGL1iDcHSC289AM6VcZNoYnBFiHXf2zn56d5
2022-09-02T17:56:48.665922764Z Serving PUT /create-anchor :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpyQmeeSJwMxwSSXJiUZfjRKz3kkBXbKauZcFChQjcvY98zR2rFzcBEreoFbEiH8MYYEY3T3B63fuifS9iP3NpKnMGL1iDcHSC289AM6VcZNoYnBFiHXf2zn56d5 4qnrBhooj78L2psbyjJ44LqFA4DA5x6Z9qWAfg4K3RNc7R5b6aXPuSeAm5NVa7Fbu1kurpLc4YJMPYZJCnmCvtpiEFAqWaUZjpUFRY8qw8ZhHiCKoceA5XA13n2P3nPLGbjdMLkB1n6enWmNZWwFP3ZkAjrp1xTM3sbTtUzfccyfLqEKeKryeQpXNAZtsnQUP39Kssk79bZRu4HKGJHf1FqQ5Xe87cNY2jwRu2ceTH
2022-09-02T17:56:48.665967023Z Call CreateAnchor for : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkpyQmeeSJwMxwSSXJiUZfjRKz3kkBXbKauZcFChQjcvY98zR2rFzcBEreoFbEiH8MYYEY3T3B63fuifS9iP3NpKnMGL1iDcHSC289AM6VcZNoYnBFiHXf2zn56d5 and [object Object]
2022-09-02T17:56:48.956413522Z Serving GET /get-last-version for  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BknwZFLswQqRHuymfrdZ6VHxhD4wbQSs5KrEoQGtEpKagJLkSVXoDRLnupVX9Pog9BAaHxU7tdg5ncqWtfnT4h1N3sdCCsWuHBwdrmPpAbtgZE5GRg2CnUG6oVhXd
2022-09-02T17:56:48.967162901Z Serving PUT /create-anchor :  2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BknwZFLswQqRHuymfrdZ6VHxhD4wbQSs5KrEoQGtEpKagJLkSVXoDRLnupVX9Pog9BAaHxU7tdg5ncqWtfnT4h1N3sdCCsWuHBwdrmPpAbtgZE5GRg2CnUG6oVhXd 4qnrBhooj78L2psbyjJ44LqFA4DA5wW1E4mdxFFJbXRQ4VneucNAMJ6dhmbNS2DwFFMczjey23YmCcG41yhBhpRYchcdjVQzeDKc3SW2WoZu6eNek2rruH1yYg22byFPUUsgKUpZx78QxZmgBYNo1R8YjGgKD6ZhxV9PHZQ5XL29zj6h1Fm5yiGyLogYWbuomKuC4TEzfS8qYBr3KqhRPPBkiBvydiy7pBhUFhjz3h
2022-09-02T17:56:48.967192871Z Call CreateAnchor for : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BknwZFLswQqRHuymfrdZ6VHxhD4wbQSs5KrEoQGtEpKagJLkSVXoDRLnupVX9Pog9BAaHxU7tdg5ncqWtfnT4h1N3sdCCsWuHBwdrmPpAbtgZE5GRg2CnUG6oVhXd and [object Object]
...
```
No errors appear on the hlf-adapter log, but possibly the /create-anchors are failing... or the response is not being properly parsed by fgt-workspace.

This setup (blockchain-hlf-workspace) is considered broken for now.

Question placed on slack anchoring-implementation on 2022-08-19 with the only answer is that nothing has changed.

The hlf-adapter version seems to be effectively frozen, but I have no idea if the install-all.sh is effectively ensuring a frozen version of HyperLedger.

**Comment by joaoluis-pdm** [comment]
During startInit.sh there was an error once...
```txt
Using organization 1
+ peer lifecycle chaincode install anchor.tar.gz
+ res=1
Error: failed to retrieve endorser client for install: endorser client failed to connect to localhost:7051: failed to create new connection: connection error: desc = "transport: error while dialing: dial tcp 127.0.0.1:7051: connect: connection refused"
Usage:
  peer lifecycle chaincode install [flags]

Flags:
      --connectionProfile string       The fully qualified path to the connection profile that provides the necessary connection information for the network. Note: currently only supported for providing peer connection information
  -h, --help                           help for install
      --peerAddresses stringArray      The addresses of the peers to connect to
      --targetPeer string              When using a connection profile, the name of the peer to target for this action
      --tlsRootCertFiles stringArray   If TLS is enabled, the paths to the TLS root cert files of the peers to connect to. The order and number of certs specified should match the --peerAddresses flag

Global Flags:
      --cafile string                       Path to file containing PEM-encoded trusted certificate(s) for the ordering endpoint
      --certfile string                     Path to file containing PEM-encoded X509 public key to use for mutual TLS communication with the orderer endpoint
      --clientauth                          Use mutual TLS when communicating with the orderer endpoint
      --connTimeout duration                Timeout for client to connect (default 3s)
      --keyfile string                      Path to file containing PEM-encoded private key to use for mutual TLS communication with the orderer endpoint
  -o, --orderer string                      Ordering service endpoint
      --ordererTLSHostnameOverride string   The hostname override to use when validating the TLS connection to the orderer
      --tls                                 Use TLS when communicating with the orderer endpoint
      --tlsHandshakeTimeShift duration      The amount of time to shift backwards for certificate expiration checks during TLS handshakes with the orderer endpoint

Chaincode installation on peer0.org1 has failed
Deploying chaincode-as-a-service failed
-------------------------------------------------------------------------------------------
...
```
but it was not clear if this is the root cause.

**Comment by joaoluis-pdm** [comment]
On 2022-09-07 the problem no longer happens.
```txt
...
Installing chaincode on peer0.org1...
Using organization 1
+ peer lifecycle chaincode install anchor.tar.gz
+ res=0
2022-09-07 12:52:50.064 UTC 0001 INFO [cli.lifecycle.chaincode] submitInstallProposal -> Installed remotely: response:<status:200 payload:"\nKanchor_1.0:db10c69ef0b441b8353494b8a9250e16e52877576aa4dc17055c649ae10e6f9b\022\nanchor_1.0" > 
2022-09-07 12:52:50.064 UTC 0002 INFO [cli.lifecycle.chaincode] submitInstallProposal -> Chaincode code package identifier: anchor_1.0:db10c69ef0b441b8353494b8a9250e16e52877576aa4dc17055c649ae10e6f9b
Chaincode is installed on peer0.org1
Install chaincode on peer0.org2...
...
```

Hummm... current hlf version is 2.4.6
